import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import WithApollo from "./withApollo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "やりたいことリスト100",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <WithApollo>
        <body className={inter.className}>{children}</body>
      </WithApollo>
    </html>
  );
}
